DROP TABLE IF EXISTS products;

CREATE TABLE products (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR(100) NOT NULL,
    price FLOAT NOT NULL,
    inventory INTEGER NOT NULL,
    CONSTRAINT PK_PRODUCT PRIMARY KEY(id)
);