language: java
jdk: openjdk11
addons:
  sonarcloud:
    organization: fpineda3105
    token:
      secure: GcBV1y1hWdvZvEHCj7AiqAndEpcCgDIjJ3rWwOxPw5h1BbrxbAGuF2bxzGbMDzwmnkg8Odto7EbQczkfMej4QDpVSMp22tUo0aQHIAmdd5AXlDYwHJNdE9NCCdoDMQJE8AJoTwtDKu6m24WBffWMrPeViaxBSuQv9b42fvXtCrJwhjo+FEniWvV/4en4f4TJ/le/SnqT0Uz01AbPNhi/IP3/vMNJe0Go5k//JOpE/5fAGx8vXPGT6GnhXJE4n7mUoadEwCE3G/pDtVYpxplRyQJXgg5H2dLGx6DzNX9LhA5Y5cwxkKap0Rdzc3pcxNyh6+hPtrJ2CiXPrnfqdX7vBSgf11nc9OfRwsEyY++OVem4IeWqhKWVV5Y6YL9U/FfyI2Fdqukss0jWXjKg4XX1t9Dt2BhkakAk4BeBBKFz8oovu5fdK/uKbCqRKoU+uEMhfEwBkmp1AxJuW8yhA0xnG8IDWy1etmL45Jp5au7RVUyBGHTdYG8XpyPJ8018mqOfub02ESuV6eIfRBLIzdkwFToOANKSUA9DZLYj3btypLK9Nf9yRanaGO1sjlSlFR0Vj2VWFQvQQYHaq8Kco/9w20euZ2xotiR3kwOnrPLeDenXpPtpbCv0V8TZKFIRHbszSSGJiO3SkKWnqv4QrLz5maYtvOERJIPm7l2dZbgO4HA=
cache:
  directories:
  - "$HOME/.m2"
before_script:
- cd choreography-pattern
- chmod a+x ./mvnw
script:
- "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=fpineda3105_java-samples"
env:
  global:
    secure: GcBV1y1hWdvZvEHCj7AiqAndEpcCgDIjJ3rWwOxPw5h1BbrxbAGuF2bxzGbMDzwmnkg8Odto7EbQczkfMej4QDpVSMp22tUo0aQHIAmdd5AXlDYwHJNdE9NCCdoDMQJE8AJoTwtDKu6m24WBffWMrPeViaxBSuQv9b42fvXtCrJwhjo+FEniWvV/4en4f4TJ/le/SnqT0Uz01AbPNhi/IP3/vMNJe0Go5k//JOpE/5fAGx8vXPGT6GnhXJE4n7mUoadEwCE3G/pDtVYpxplRyQJXgg5H2dLGx6DzNX9LhA5Y5cwxkKap0Rdzc3pcxNyh6+hPtrJ2CiXPrnfqdX7vBSgf11nc9OfRwsEyY++OVem4IeWqhKWVV5Y6YL9U/FfyI2Fdqukss0jWXjKg4XX1t9Dt2BhkakAk4BeBBKFz8oovu5fdK/uKbCqRKoU+uEMhfEwBkmp1AxJuW8yhA0xnG8IDWy1etmL45Jp5au7RVUyBGHTdYG8XpyPJ8018mqOfub02ESuV6eIfRBLIzdkwFToOANKSUA9DZLYj3btypLK9Nf9yRanaGO1sjlSlFR0Vj2VWFQvQQYHaq8Kco/9w20euZ2xotiR3kwOnrPLeDenXpPtpbCv0V8TZKFIRHbszSSGJiO3SkKWnqv4QrLz5maYtvOERJIPm7l2dZbgO4HA=
