language: java
jdk: openjdk11
addons:
  sonarcloud:
    organization: fpineda3105
    token:
      secure: "rVOhc8I98MFKvFzbpr6iNZMK0TzHfi87NkUcJR2YkeY78HyHnaKsIMHEmT8Y9BiCqK/zEyKslQY9NFVpVfPr3qWCKHo8doM3bxFaXi32jCRbtUX5Sd0FrDR3iWZCChfk8gZCl3AkLGYQu9QYOsJeB30yUFC1WK2DzB1MxAGvsly81UcmBvViNP5wJfI+eRHSmYbvGBQw98Md0bzJxkeB4XVukT9kTlq11XSIqMnOStx3WMcu3vGNNrqwNbAsEQCNj5mTEiCrep6lKDFseadjMuhwIm0DzMCrv+4EUFbJMUM5X8gklZ2be3eOFe8zDqY8TzrpRlyedUVoudN1LFTKmz8djEHBdGNjK9dtqDo+WIDoqP8fY1UTgXDsPpYofjy77V76l05E4PrT0iUol5duOJ9OmL4VCod7Dre+3m5JEN7Phn6koWDBXPL/SnRFkVDYXt7rddJzKxR7d3cPxwBG4vBmNjRmdoKx+/pi/VyjugTrWsdesgNA5GKaEASi7rxZitcR+Uqec8RJGC9noa/93NnJMcOtufdsuwj3gtW8Ay08ScNbTQd1/Zo9Ei3Fiu1PLh+gvodLs7+G7sve5WpWYIpws17Cb2PRvalMEssnW6zKyP710x/hN3yTNuD+zNH2QuxmAfB73KXLBW+xeWMUgpN3ntbwS0c5Se0XkzfRzH8="
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.sonar/cache"
before_script:
  - cd choreography-pattern
  - chmod a+x ./mvnw
script:
  - "./mvnw clean install sonar:sonar -Dsonar.projectKey=fpineda3105_java-samples"

